baseurl = "https://evnt.center/"
languageCode = "en-us"
title = "evnt.center"
# theme
theme = "hugo-now"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-103951186-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Event & Conference Information Hub"
  author = "Matt McGrath"
  keywords = ["conference"]
  avatar = "/images/icons8-Arena-50.png"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"
  custom_css = ["css/override.css"]