baseurl = "https://evnt.center/"
languageCode = "en-us"
title = "evnt.center"
# theme
theme = "hugo-now"
# google analytics
GoogleAnalytics = "UA-103951186-1"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  description = "evnt.center | The Event and Conference Information Hub. Focused on Technology Industry Gatherings. Giving you the details you need to find your next best Conference Experience."
  author = "Matt McGrath"
  keywords = ["conference"]
  avatar = "/images/icons8-Arena-Filled-50.png"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"
  custom_css = ["css/override.css"]