---
hide_body: false
fields:
- name: date
  label: Date
  type: field_group
  hidden: false
  default: {}
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - project
- name: description
  label: Description
  type: text
  hidden: false
  default: A project on Github
- name: repo
  label: Repo
  type: text
  hidden: false
  default: ''
- name: website
  label: Website
  type: text
  hidden: false
  default: ''
